### ISSUE TITLE
Im sorry for asking but is there anyway we can change usernames?

### ISSUE THREAD

**Issue by verzide-pixel** [BorgGames/Minecraft#3]

**Comment by verzide-pixel** [comment]
im sorry for asking but can we?

**Comment by verzide-pixel** [comment]
it will be fine if we can't I'm just curious because i really want to play with other players that play on this awesome client

**Comment by lostmsu** [comment]
If you own Minecraft, you should be able to change name using the official Minecraft website (after logging in): https://www.minecraft.net/en-us/msaprofile/mygames/editprofile

If you don't, you should not really be playing trial over and over again.

P.S. Please close this issue if you are able to change your name.
